/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testGradle2;

//import static org.junit.Test;
import org.junit.jupiter.api.*;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        Assertions.assertTrue(classUnderTest.someLibraryMethod());
    }
}
